global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'reb-elearning'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'mysql'
    static_configs:
      - targets: ['localhost:9104']

  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']

  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:9113']

  - job_name: 'php-fpm'
    static_configs:
      - targets: ['localhost:9253']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
